name: fingertap
description: Fast reaction game with tapping multiple fingers on the screen.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  hive: ^2.2.3
  path_provider: ^2.1.3
  device_info_plus: ^10.1.0

  # Firebase
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
